# ----
# Site

title: EMIT
url: "http://adored-pea.cloudvent.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key: AIzaSyCL26-sipFBbMnRYXRf_QAaa3Zp6eZmGUc
snipcart_key: "NWFiMDUzOWItMDg2Yi00MDhjLWE1YmItODQ0M2EwYTI5YWI1NjM3MzU3Nzg2ODIyNjc0NDAz"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Transforming Nations by Training Leaders
author:
  name: EMIT
  email: admin@emit.global
  twitter: EMITglobal # twitter username without the @ symbol
  phone: "+27 11 362 6655"
social:
  name: EMIT
  links:
    - https://emit.global/
    - https://www.facebook.com/EMIT.global/
    - https://twitter.com/EMITglobal/

# -----
# Build
timezone: Africa/Johannesburg

collections:
  programs:
    _hide_content: true
    _icon: school
    _image_key:	bookCover_image
    _image_size: cover
    output: true
    sort_by: id
  products:
    _hide_content: true
    _icon: shopping_cart
    output: true

permalink: /:title.html

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
      bookCover_image: /images/programs/NewProgramTrainingBook.webp
      curriculumSprite_image: /images/sprites/sprite-Set2.webp
  -
    scope:
      path: ""
    values:
      layout: "page"
      # defaults for hero where nothing has been set
      heroQuote: The essence of leadership is to make a difference in your sphere of influence.
      hero_Quote_Cite: O O Isaac
      hero_image: /images/couple.webp
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "_data"
    values:
      hero_image: "" # or any placeholder image you want

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-maps

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# MAP PLUGIN NEEDS GOGGLE API
maps:
  google:
    api_key: AIzaSyCopZOMs4afUxxRSYN36lBdL5dzANTsvFA

# -----------
# CloudCannon
_explore:
  groups:
    - heading: Pages
      collections:
        - pages
    - heading: Articles
      collections:
        - posts
        - drafts
    - heading: Data-Lists
      collections:
        - programs
        - products
        - data

# Sonya changed this to donation types
garment_types:
  - hat
  - top
# SELECT FIELD: Program Status determines whether program can be viewed
statuses:
  - current
  - planned
  - developing
# SELECT FIELD: Team members are categorised in groups
groups:
  - team
  - board

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
# Hero image for all page headers
  hero_image:
    uploads_dir: "images/:title"
# Profile Image in data/team
  profile_image: # Front matter field
    uploads_dir: "images/team/:title"
    width: 500
    height: 500
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true
# Partner Logo in data/
  partner_image: # Front matter field
    uploads_dir: "images/partners/:title"
    width: 132
    height: 140
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true
# Program Image uploads
  bookcover_image: # Front matter field
    uploads_dir: "images/programs/:title"
  curriculumSprite_image:
    uploads_dir: "images/programs/:title"
# Leader/Student profile image for transformation stories - called image to be compatible with maps plugin
  image:
    uploads_dir: "images/leaders/:title"

_comments:
  id: Give this item an id number or code. Does not normally display anywhere on the front-end but sometimes used to sort a list when displaying it on a page.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background color used in the plan name and call to action.
  new_window: Open link in new window
  description: This is used for facebook shares of the page and google indexing
  status: Current/Planned/Developing. Current- open for registration. Developing- visible for sponsorship. Planned- visible only in lists.
  image: Student / Leader profile image (500px X 500px) displays in map and sidebar for transformation stories
  leaderBio_description: Displays in sidebar on transformation story posts
  bio_html: Short paragraph or two about this person
  heroQuote: Featured inspirational quote to display on page header image
  hero_Quote_Cite: Ascribe the quote or author
  hero: Alternative title to display on page header. Default is page title
  hero_image: The large featured image at the top of the page. Should be at least 3000px wide.
  bookCover_image: The cover of the program book. Speak to Sonya about creating the mockups.
  curriculumSprite_image: To minimise loading time - all the corricula images are compiled as a single sprite. Speak to sonya about creating these and linking them.
  title: This will be the page url.
  subtitle: Clickbait. In one sentence describe why this content is interesting to the reader