# ----
# Site

title: EMIT
url: "http://adored-pea.cloudvent.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key: AIzaSyCL26-sipFBbMnRYXRf_QAaa3Zp6eZmGUc
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Transforming Nations by Training Leaders
author:
  name: EMIT
  email: admin@emit.global
  twitter: EMITglobal # twitter username without the @ symbol
  phone: "+27 11 362 6655"
social:
  name: EMIT
  links:
    - https://emit.global/
    - https://www.facebook.com/EMIT.global/
    - https://twitter.com/EMITglobal/

# -----
# Build
timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
    _icon: account_circle
  products:
    _hide_content: true
    output: true
    _icon: shopping_cart
  programs:
    _hide_content: true
    output: true
    _icon: school
    sort_by: id

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-maps

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# MAP PLUGIN NEEDS GOGGLE API
maps:
  google:
    api_key: AIzaSyCL26-sipFBbMnRYXRf_QAaa3Zp6eZmGUc

# -----------
# CloudCannon

garment_types:
  - hat
  - top
# Program Status determines whether program can be viewed
statuses:
  - current
  - planned
  - developing
# Team members are categorised in groups
groups:
  - team
  - board

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  profile_image: # Front matter field
    uploads_dir: "images/team/:title"
    width: 500
    height: 500
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true
  partner_image: # Front matter field
    uploads_dir: "images/partners/:title"
    width: 132
    height: 140
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background color used in the plan name and call to action.
  new_window: Open link in new window
  description: This is used for facebook shares of the page and google indexing
  status: Current/Planned/Developing. Developing programs will be visible for spoonsorship.
  image: Student / Leader profile image (500px X 500px) displays in map and sidebar for transformation stories
  leaderBio_description: Displays in sidebar on transformation story posts
  bio_description: Short paragraph about this person